source("common.R")
png("plot3.png", width=480, height=480)
par(lty='solid')
with(ds0207, {
    plot(datetime, Sub_metering_1, type="l", xlab="", col="black", ylab="Energy sub metering")
    lines(datetime, Sub_metering_2, type="l", xlab="", col="red")
    lines(datetime, Sub_metering_3, type="l", xlab="", col="blue")
})
legend("topright", lty=c(1,1), col=c("black","red","blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()
